#!/usr/bin/python3

"""This module factorizes as many numbers as possible
   into a product of two smaller numbers."""

from sys import argv


def factorize(file_name):
    """factorize the given number into a product of two smaller numbers."""
    with open(file_name) as file:
        for val in file.readlines():
            number = int(val)
            for i in range(2, number):
                if number == ((number // i) * i):
                    print("{}={}*{}".format(number, (number // i), i))
                    break


for i in range(1, len(argv)):
    factorize(argv[i])
