#!/usr/bin/python3

"""This module factorizes as many numbers as possible
   into a product of two smaller numbers."""

from sys import argv


def factorize():
    """factorize the given number into a product of two smaller numbers."""
    with open(argv[1], encoding="utf-8") as file:
        for val in file.readlines():
            number = int(val)
            for i in range(2, number):
                if number == ((number // i) * i):
                    print("{}={}*{}".format(number, (number // i), i))
                    break


if len(argv) == 2:
    factorize()
